# Generated by Django 4.1.6 on 2023-02-12 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BankUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='openDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
